### Crear una orden
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "name": "Felipe Fernández",
  "address": "Calle Falsa 123",
  "phone": "1122334455",
  "paymentMethod": "Tarjeta de crédito",
  "items": [
    {
      "id": "ID_DEL_PRODUCTO_1",
      "quantity": 2
    },
    {
      "id": "ID_DEL_PRODUCTO_2",
      "quantity": 1
    }
  ]
}

### Obtener orden por ID
//GET http://localhost:3000/api/orders/{{orderId}}

### Listar todas las órdenes (admin)
GET http://localhost:3000/api/orders

